// Code generated by mockery v2.53.7. DO NOT EDIT.

package services_mocks

import (
	model "github.com/pvlearning002/go_assignment01/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheckMock is an autogenerated mock type for the HealthCheckMock type
type HealthCheckMock struct {
	mock.Mock
}

// GenerateHealthCheck provides a mock function with no fields
func (_m *HealthCheckMock) GenerateHealthCheck() *model.HealthCheck {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateHealthCheck")
	}

	var r0 *model.HealthCheck
	if rf, ok := ret.Get(0).(func() *model.HealthCheck); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.HealthCheck)
		}
	}

	return r0
}

// NewHealthCheckMock creates a new instance of HealthCheckMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckMock {
	mock := &HealthCheckMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
